server:
  port: 8090

spring:
  application:
    name: optimal-choice-app
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_APP_USER:optimal_choice_user}
    password: ${DB_APP_PASSWORD:optimal_choice_password}
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
    schemas: optch
    baseline-on-migrate: false
    validate-on-migrate: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: optch
        max_fetch_depth: 3
        order_inserts: true
        order_updates: true
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: validate
    generate-ddl: true

springdoc:
  api-docs:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: db-debug
  jpa:
    properties:
      hibernate:
       generate_statistics: true
       format_sql: true
    show-sql: true
    generate-ddl: true

logging:
 level:
   org:
     hibernate:
       stat: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev-h2
  datasource:
   url: jdbc:h2:file:./opttestdb_v2
   username: sa
   password: my-psw
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
       generate_statistics: true
       format_sql: true
    show-sql: true
    generate-ddl: true
  h2:
    console.enabled: true

logging:
 level:
   org:
     hibernate:
       stat: DEBUG
